feat "добавил базу данных, броинрования, отзывы"
SafiulinRM/java-shareit pull request #2
Opened 2022-09-13 13:07 UTC by SafiulinRM

2022-09-14 21:33 UTC, makholin commented
В коммиты нужно писать сообщения с информацией, что было сделано

Вот например, как выглядят сообщения коммитов в самом спринге: https://github.com/spring-projects/spring-framework/commits/main

2022-09-14 21:35 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private State status;
стоит название поля и название класса сделать одинаковым
либо это State state, либо Status status

2022-09-14 21:36 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public static final String HEADER_OF_OWNER = "X-Sharer-User-Id";
лучше назвать OWNER_ID_HEADER или USER_ID_HEADER

и константы стоит отделять пустой строкой от других полей класса

2022-09-14 21:38 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoInfo.java
> +public class BookingDtoInfo {
по названиям BookingDto и BookingDtoInfo не понятно, в чем их отличие и какой где нужно использовать

2022-09-14 21:41 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                .stream().map(BookingMapper::toBookingDtoInfo).collect(toList());
для стримов каждый вызов функций лучше делать на отдельных строках
```
list.stream()
.filter(...)
.map(...)
.collect(...)
```

2022-09-14 21:42 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                        @RequestParam(required = false, defaultValue = "ALL") String state) {
ALL стоит вынести в константу как `DEFAULT_STATE`

2022-09-14 21:45 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findByBooker_IdOrderByStartDesc(long userId);
jpa синтаксис в названиях методов должен работать и без _

2022-09-14 21:49 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            if (newBooking.getStatus().equals(State.APPROVED)) {
код с таким количеством условий тяжело понимать, тестировать и изменять

нужно отрефакторить код, избавиться от вложенных if в друг друга и конструкций else-if

2022-09-14 21:55 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            throw new NotFoundException("Approve the booking failed");
название исключения говорит о том, что что-то не найдено
но в сообщении говорится о том, что просто подтверждение зафейлилось без каких-либо деталей

стоит сделать более очевидно

2022-09-14 21:57 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            throw new NotFoundException("The user is not associated with the booking: " + userId);
тут тоже NotFoundExc не очень подходит 
нужно исправить исключения на более очевидные, можно сделать какое-нибудь общее BookingException

2022-09-14 22:01 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    public Collection<Booking> getBookingsOfUser(long userId, String status) {
статус лучше смапить в enum в контроллере и в сервисах уже использовать тип енума а не строки

2022-09-14 22:13 UTC, makholin commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
еще нужен обработчик общих исключений (Throwable)
и отвечать http 500

2022-09-14 22:17 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    Long id;
нужно поля сделать private

2022-09-14 22:20 UTC, makholin requested changes
Нужно исправить замечания

2022-09-16 12:06 UTC, SafiulinRM commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    public Collection<Booking> getBookingsOfUser(long userId, String status) {
Тоже думал так сделать, но в контроллер могут прийти такие статусы как: "ALL", "CURRENT", "PAST", "FUTURE", но у нас энамы только public enum State {
    WAITING,
    APPROVED,
    REJECTED,
    CANCELED
} как тогда поступть?

2022-09-16 12:44 UTC, SafiulinRM commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
я уже так делал, если сделать обработчик общих исключений, то он другие исключения не будет видеть и всегда будет выдавать ответ 500

2022-09-19 13:27 UTC, TyutterinYakov reviewed
Добрый день! В целом - хорошо) Отметил то, что следует исправить и то, что можно сделать лучше) Хорошего дня! Если возникнут вопросы - пиши в слак, буду рад помочь🌅

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
В данном случае следует возвращать статус 400 BAD_REQUEST, так как некорректные данные пришли от пользователя

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
>  @RestControllerAdvice
В класс следует добавить логирование) Для этого достаточно использовать аннотацию из lombok ->> [@slf4j](https://github.com/slf4j). Далее в каждый наш хендлер следует добавить логирование сообщения об ошибке)
Так же следует добавить хендлер для обработки всех необработанных исключений, ловить будем Throwable, а возвращать статус 500 INTERNAL_SERVER_ERROR
Так же тесты после этого упадут, так как не добавлен обработчик для исключения, которое выбрасывается при валидации данных с помощью аннотаций - MethodArgumentNotValidException

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Я выше отписал, как можно поступить) Должно помочь)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +
(предложение)Можно добавить такую аннотацию
@NoArgsConstructor(access = AccessLevel.PRIVATE)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserService.java
>  @RequiredArgsConstructor
Хорошо было бы во всех сервисах работать с транзакциями. Для этого над классом достаточно навесить аннотацию @transactional(readOnly = true), таким образом мы укажем, что изменения в сущностях не будут фиксировать в БД, а для того, чтобы фиксация в некоторых методах происходила по завершению транзакции, достаточно над этим методом навесить @transactional
А так же, если возникнет непроверямое исключение, все изменения в пределах транзакции будут откатаны назад) Так же не нужно будет при обновлении вызывать save репозитория, если производится изменение полученной сущности, так как они будут зафиксированы после завершения транзакции)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        userRepository.save(newUser);
То есть при использовании @Transactional не нужно будет вызывать метод save, так как изменения будут зафиксированы в полученной сущности из бд)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
>      }
(предложение)Можно добавить такую аннотацию
@NoArgsConstructor(access = AccessLevel.PRIVATE)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +                .map(user -> toUserDto(user))
Можно было бы использовать референц выражение)
.map(UserDto::toUserDto)..
Так же преобразование List<User> в List<UserDto> хорошо было бы вынести в отдельный метод в маппере, так как преобразованиями должен заниматься он)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/User.java
>      private String name;
Хорошо было бы над полем name добавить аннотацию @Column с параметром nullable = false, таким образом мы ограничим добавление записей без имени)
Аналогично и с почтой, где дополнительно можно указать максимальный размер, например, length = 512

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private long ownerId;
Можно было бы указать связь с таблицей Users
@manytoone(optional = false)
@joincolumn(name = "owner_id", nullable = false)
private User owner;
Вместо того, чтобы хранить только идентификатор) Таким образом при необходимости мы сможем из предмета сразу же получить пользователя)
nullable = false указывает на то, что ячейка не может быть пустой, а optional = false указывает, что связь является обязательной

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@ToString
Если требуется метод @ToString то его следует в классе-сущности задавать вручную, так как, если он будет вызван вне транзакции, может возникнуть исключение

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@ToString
Аналогично, @ToString следует убрать

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    @Id
Для соблюдения инкапсуляции поля класса должны быть приватными

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    LocalDateTime created;
Время можно было бы проинициализировать при создании объекта этого класса)
 = LocalDateTime.now();

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    String text;
Над полем с текстом хорошо было бы добавить ограничение)
@Column(name = "text", nullable = false, length = 4000)
На размер и на то, что он точно есть)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemRepository.save(newItem);
Здесь так же не нужно будет вызывать save при работе с транзакцией записи)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
(предложение)Можно добавить такую аннотацию
@NoArgsConstructor(access = AccessLevel.PRIVATE)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +            "order by b.start desc")
Можно было бы оставить возможность выбора сортировки, чтобы в случае, когда нам потребуется другой порядок - не писать еще один метод) Для этого в аргументах метода следует так же ожидать Sort sort.
Объект этого класса создается подобным образом: Sort.by(Sort.Direction.DESC, "start");
А order by b.start следовательно нужно будет убрать)
Аналогично и с другими методами)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +
(предложение)Можно добавить такую аннотацию
@NoArgsConstructor(access = AccessLevel.PRIVATE)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoInput.java
> +    @NotNull(groups = {Create.class})
Можно было бы так же использовать аннотации @FutureOrPresent и @Future над полями start и end) Таким образом можно было бы избавиться от части проверок в коде)

2022-09-19 13:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (booking.getStart().isAfter(booking.getEnd()) ||
!booking.getStart().isBefore(booking.getEnd()) можно две проверки заменить на одну)
То есть время старта после либо равно времени окончания) В этом случае мы и будем выбрасывать исключение

2022-09-19 16:23 UTC, SafiulinRM commented on src/main/java/ru/practicum/shareit/user/User.java
>      private String name;
а то что у меня на входящем дто валидация стоит этого не хватит?public class UserDto {
    private Long id;
    @NotBlank(groups = {Create.class})
    private String name;
    @Email(groups = {Create.class, Update.class})
    @NotBlank(groups = {Create.class})
    private String email;
}

2022-09-21 13:08 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/User.java
>      private String name;
Да, но это валидация тех данных, которые поступают из вне, но мы так же должны обезопасить себя от ошибок в случае, например, если маппер будет некорректно реализован и будет упускаться установка значения какого-то поля

2022-09-21 14:16 UTC, TyutterinYakov approved these changes
Добрый день! Поздравляю с успешной сдачей спринта! Сил и терпения на этом сложном, но интересном пути! Хорошего дня и отличного настроения🌅🎇

2022-09-21 15:25 UTC, merged